version: 2

build:
  image: latest

python:
  version: 3.9
  install:
    - method: pip
      path: .

conda:
  environment: environment.yml
  
sphinx:
  builder: html
  configuration: doc/conf.py
  fail_on_warning: false